checkpoint_freq: 1000
display_freq: 1000
model_type: F
model_in_channels: 3
model_z_channels : 64
model_out_batch_norm : False
dataset: celeba
dataset_size: full

batch_size: 30
epochs: 24
opt_level: O2