checkpoint_freq: 1000

model_type: VGG_PONG_LAYERNECK
model_in_channels: 1
model_z_channels : 16
model_keypoints : 3

dataset: pong
dataset_train_len: 19000
dataset_test_len: 1100
dataset_randomize: True
data_aug_type: None

batch_size: 120
epochs: 1000
opt_level: O2
